name: tracking_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  firebase_analytics: ^9.1.11
  firebase_core: ^1.19.0
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
