// Mocks generated by Mockito 5.1.0 from annotations
// in ax_dapp/test/GetSellInfoUseCase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:ax_dapp/repositories/subgraph/usecases/GetSwapInfoUseCase.dart'
    as _i3;
import 'package:fpdart/fpdart.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetSwapInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSwapInfoUseCase extends _i1.Mock
    implements _i3.GetSwapInfoUseCase {
  MockGetSwapInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i3.Success, _i3.Error>> fetchSwapInfo(
          {String? tokenFrom,
          String? tokenTo,
          double? fromInput,
          double? slippage}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchSwapInfo, [], {
                #tokenFrom: tokenFrom,
                #tokenTo: tokenTo,
                #fromInput: fromInput,
                #slippage: slippage
              }),
              returnValue: Future<_i2.Either<_i3.Success, _i3.Error>>.value(
                  _FakeEither_0<_i3.Success, _i3.Error>()))
          as _i4.Future<_i2.Either<_i3.Success, _i3.Error>>);
}
