name: tokens_repository
description: Repository that manages the token domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ethereum_api:
    path: ../ethereum_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
