targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/service/api/models/**.dart
            - lib/service/athlete_models/**.dart
            - lib/service/blockchain_models/**.dart
            - test/**.dart
        options:
          explicit_to_json: true
          include_if_null: false