name: wallet_repository
description: Repository that manages the wallet domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cache:
    path: ../cache
  ethereum_api:
    path: ../ethereum_api
  shared:
    path: ../shared
  shared_preferences: ^0.5.5

dev_dependencies:
  mocktail: ^0.3.0
  test: 1.21.4
  very_good_analysis: ^3.0.1

dependency_overrides:
  async: 2.8.2
  meta: 1.8.0
