image:
  repository: 510626941593.dkr.ecr.us-east-1.amazonaws.com
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  containerPort: 5050

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
