name: ethereum_api
description: Ethereum API clients
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web3: ^2.1.9
  shared:
    path: ../shared

dependency_overrides:
  async: 2.8.2
  meta: 1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1


