// Mocks generated by Mockito 5.1.0 from annotations
// in ax_dapp/test/service/Controller/usecases/GetChainChangesUseCase_test.dart.
// Do not manually edit this file.

import 'package:ax_dapp/util/EthereumChainWrapper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [EthereumWebChainWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockEthereumWebChainWrapper extends _i1.Mock
    implements _i2.EthereumWebChainWrapper {
  MockEthereumWebChainWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic onChainChanged(void Function(int)? listener) =>
      super.noSuchMethod(Invocation.method(#onChainChanged, [listener]));
}
