name: use_cases
description: Collection of app specific use cases.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  config_repository:
    path: ../config_repository
  shared:
    path: ../shared
  tokens_repository:
    path: ../tokens_repository
  wallet_repository:
    path: ../wallet_repository

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

dependency_overrides:
  meta: 1.8.0

