// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:ax_dapp/app/config/app_config.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      FirebaseOptions firebaseConfigs;
      try {
        firebaseConfigs =
            (buildConfig == BuildConfig.release) ? webRelease : webRelease;
      } catch (e) {
        firebaseConfigs = webRelease;
      }
      return firebaseConfigs;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return webRelease;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions webRelease = FirebaseOptions(
    apiKey: 'AIzaSyBev41Rd-3rxDdqfc7mceAix785rVzIMPY',
    authDomain: 'athletex-prod.firebaseapp.com',
    projectId: 'athletex-prod',
    storageBucket: 'athletex-prod.firebasestorage.app',
    messagingSenderId: '621355421546',
    appId: '1:621355421546:web:410b581282fb92241adf13',
    measurementId: 'G-QG8RMDHJTE',
  );
}
