name: user_authentication
description: "Manages user auth"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  cryptography: ^2.5.0
  encrypt: ^5.0.3
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  wallet_repository:
    path: ../wallet_repository

dependency_overrides:
  meta: 1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
