name: league_repository
description: Repository that manages the leagues.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  ethereum_api:
    path: ../ethereum_api
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dependency_overrides:
  async: 2.8.2
  meta: 1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.2
  test: ^1.21.4
  very_good_analysis: ^3.0.1
