name: config_repository
description: Repository that manages configurations.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ethereum_api:
    path: ../ethereum_api
  shared:
    path: ../shared

dependency_overrides:
  meta: 1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1


