# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
        
      # View the installed Dart version 
      - name: View Latest Version
        run: dart --version

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: / #this needs to be updated
          # The desired behavior if no files are found using the provided path.
# Available Options:
#         warn: Output a warning but do not fail the action
#         error: Fail the action with an error message
#         ignore: Do not output any warnings or errors, the action does not fail

#         if-no-files-found: # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention.
        #Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
#         retention-days: # optional
