# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Release EC2

on:
  push:
    branches:
      - 'develop'
jobs:
  deploy:
    name: Deploy Staging Build to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to US-East-1 (NVirginia) EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_DNS }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.AWS_EC2_SSH_PORT }}
          script: 'cd /home/ax_dapp_staging &&
          git fetch &&
          git reset --hard origin/develop &&
          ./launch_container.sh'