on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build-prod:
    runs-on: ubuntu-latest
    name: Build, create docker image, and push on PR merge
    steps:
      - uses: actions/checkout@v2
      - name: AthleteX Dapp
        id: deploy
        uses: fleekhq/action-deploy@v1

      - name: Get Code
        uses: actions/checkout@v3

        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}

      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
